"""add_location_field

Revision ID: b91e6d50c006
Revises: 20260325_000001
Create Date: 2026-03-25 11:56:52.435390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'b91e6d50c006'
down_revision: Union[str, Sequence[str], None] = '20260325_000001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('location', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_applications', 'location')
    # ### end Alembic commands ###
